unique_ids:
  assets:
    standard-page.html: OMZZGPOV3ZX52FRC7K2QUWT2H3KL43U2
    theme.css: PKU47AONEYEJ35OP5R5OFQARH5EVZQK5
  forms:
    Form1: 4XEKOVJYWBZKXD6KJNP7LMLJUXYHGUF2
  modules: {}
  scripts: {}
  server_modules: {}
